apiVersion: v1
kind: Service
metadata:
  name: caiway
spec:
  type: LoadBalancer
  selector:
    app: caiway
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: caiway
  labels:
    app: caiway
spec:
  replicas: 3
  selector:
    matchLabels:
      app: caiway
  template:
    metadata:
      labels:
        app: caiway
    spec:
      containers:
        - name: caiway
          image: pavelatcai/totheroots
          ports:
            - containerPort: 8080